version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
  hasura:
#    image: hasura/graphql-engine:v1.0.0-alpha37
    image: hasura/graphql-engine:v1.0.0-alpha37.cli-migrations
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@localhost:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_MIGRATIONS_DIR:
      ## execute ./toos/encode_jwt_secret.py to obtain HASURA_GRAPHQL_JWT_SECRET from Flask config
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "slkd1o8wnO*#LUFHNO4islkd1o8wnO*#"}'
      ## uncomment next line to set an access key
      HASURA_GRAPHQL_ACCESS_KEY: devaccess
    volumes:
      - ./hasura/migrations:/hasura-migrations
    network_mode: "host"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    restart: always
    environment:
      CONFIG_FILE_PATH: docker-compose-config.py
    entrypoint: ["flask", "run", "--host", "0.0.0.0"]
    network_mode: "host"
volumes:
  hasura_migrations:
  db_data:
