version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v1.0.0-alpha37
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_MIGRATIONS_DIR:
      ## uncomment next line to set an access key
      # HASURA_GRAPHQL_ACCESS_KEY: mysecretaccesskey
    volumes:
      - ./hasura/migrations:/hasura-migrations
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      HASURA_GQL: http://hasura:8080/v1alpha1/graphql
    entrypoint: ["flask", "run", "--host", "0.0.0.0"]
volumes:
  hasura_migrations:
  db_data:
