- args:
    permission:
      allow_aggregations: false
      columns:
      - id
      - name
      - repository_id
      - project_id
      - type_id
      filter:
        projectByprojectId:
          userProjectsByprojectId:
            user_id:
              _eq: X-HASURA-USER-ID
      limit: null
    role: reader
    table:
      name: configuration
      schema: public
  type: create_select_permission
