- args:
    role: manager
    table:
      name: configuration
      schema: public
  type: drop_insert_permission
- args:
    permission:
      check:
        project:
          userProjects:
            user_id:
              _eq: X-HASURA-USER-ID
      columns:
      - name
      - project_id
      - repository_id
      - type_id
      set: {}
    role: manager
    table:
      name: configuration
      schema: public
  type: create_insert_permission
