- args:
    name: configurations
    table:
      name: test_creator
      schema: public
    using:
      foreign_key_constraint_on:
        column: test_creator_id
        table:
          name: test_creator_configuration_m2m
          schema: public
  type: create_array_relationship
