- args:
    name: repositories
    table:
      name: configuration_type
      schema: public
    using:
      foreign_key_constraint_on:
        column: type_slug
        table:
          name: repository
          schema: public
  type: create_array_relationship
