- args:
    role: testrunner
    table:
      name: configuration_parameter
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns:
      - id
      - configuration_id
      - value
      - parameter_slug
      filter:
        configuration:
          executions:
            id:
              _eq: X-Hasura-Testruner-Id
    role: testrunner
    table:
      name: configuration_parameter
      schema: public
  type: create_select_permission
