- args:
    sql: ALTER TABLE "public"."test_creator_configuration_m2m" ALTER COLUMN "test_creator_id"
      DROP NOT NULL;
  type: run_sql
- args:
    sql: COMMENT ON COLUMN "public"."test_creator_configuration_m2m"."test_creator_id"
      IS ''
  type: run_sql
