- args:
    name: configurations
    table:
      name: test_source
      schema: public
    using:
      foreign_key_constraint_on:
        column: test_source_id
        table:
          name: configuration
          schema: public
  type: create_array_relationship
