- args:
    role: testrunner
    table:
      name: configuration
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns:
      - created_by_id
      - id
      - name
      - performed
      - project_id
      - type_slug
      filter:
        executions:
          id:
            _eq: X-Hasura-Testruner-Id
    role: testrunner
    table:
      name: configuration
      schema: public
  type: create_select_permission
