- args:
    name: parameters
    table:
      name: configuration_type
      schema: public
    using:
      foreign_key_constraint_on:
        column: type_slug
        table:
          name: parameter
          schema: public
  type: create_array_relationship
