- args:
    role: manager
    table:
      name: configuration
      schema: public
  type: drop_update_permission
- args:
    permission:
      columns:
      - name
      - project_id
      filter:
        _and:
        - project:
            userProjects:
              user_id:
                _eq: X-Hasura-User-Id
        - performed:
            _eq: false
      localPresets:
      - key: created_by_id
        value: x-hasura-User-Id
      - key: ""
        value: ""
      set:
        created_by_id: x-hasura-User-Id
    role: manager
    table:
      name: configuration
      schema: public
  type: create_update_permission
