- args:
    role: testrunner
    table:
      name: configuration_envvars
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns: []
      filter:
        configuration:
          executions:
            id:
              _eq: X-Hasura-Testruner-Id
    role: testrunner
    table:
      name: configuration_envvars
      schema: public
  type: create_select_permission
