- args:
    role: testrunner
    table:
      name: configuration_envvars
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: true
      columns:
      - id
      - configuration_id
      - name
      - value
      filter:
        configuration:
          executions:
            id:
              _eq: X-Hasura-Testruner-Id
    role: testrunner
    table:
      name: configuration_envvars
      schema: public
  type: create_select_permission
