- args:
    name: extension_params
    table:
      name: configuration_extension
      schema: public
    using:
      foreign_key_constraint_on:
        column: configuration_extension_id
        table:
          name: extension_params
          schema: public
  type: create_array_relationship
