- args:
    role: manager
    table:
      name: configuration_type
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: true
      columns:
      - id
      - name
      - description
      - slug_name
      filter: {}
    role: manager
    table:
      name: configuration_type
      schema: public
  type: create_select_permission
