- args:
    permission:
      allow_aggregations: true
      columns:
      - created_by_id
      - id
      - instances
      - name
      - performed
      - project_id
      - test_source_id
      - type_slug
      filter:
        _and:
        - executions:
            id:
              _eq: X-Hasura-User-Id
        - project:
            is_deleted:
              _eq: false
        - is_deleted:
            _eq: false
    role: reader
    table:
      name: configuration
      schema: public
  type: create_select_permission
- args:
    role: reader
    table:
      name: configuration
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: true
      columns:
      - created_by_id
      - id
      - instances
      - name
      - performed
      - project_id
      - test_source_id
      - type_slug
      filter:
        _and:
        - executions:
            id:
              _eq: X-Hasura-User-Id
        - project:
            is_deleted:
              _eq: false
        - is_deleted:
            _eq: false
    role: tester
    table:
      name: configuration
      schema: public
  type: create_select_permission
- args:
    role: tester
    table:
      name: configuration
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: true
      columns:
      - id
      - name
      - project_id
      - performed
      - created_by_id
      - type_slug
      - test_source_id
      - instances
      - is_deleted
      - has_pre_test
      - has_post_test
      - has_load_tests
      - has_monitoring
      - monitoring_chart_configuration
      filter:
        _and:
        - project:
            userProjects:
              user_id:
                _eq: X-Hasura-User-Id
        - project:
            is_deleted:
              _eq: false
        - is_deleted:
            _eq: false
    role: manager
    table:
      name: configuration
      schema: public
  type: create_select_permission
- args:
    role: manager
    table:
      name: configuration
      schema: public
  type: drop_select_permission
