- args:
    permission:
      allow_aggregations: true
      columns:
      - description
      - id
      - name
      - slug_name
      filter: {}
      limit: null
    role: tester
    table:
      name: configuration_type
      schema: public
  type: create_select_permission
