- args:
    role: reader
    table:
      name: configuration_type
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns:
      - id
      - name
      - description
      filter: {}
    role: reader
    table:
      name: configuration_type
      schema: public
  type: create_select_permission
