- args:
    permission:
      allow_aggregations: false
      columns:
      - configuration_id
      - id
      - parameter_slug
      - value
      filter:
        configuration:
          project:
            userProjects:
              user_id:
                _eq: X-HASURA-USER-ID
    role: manager
    table:
      name: configuration_parameter
      schema: public
  type: create_select_permission
- args:
    role: manager
    table:
      name: configuration_parameter
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns:
      - configuration_id
      - id
      - parameter_slug
      - value
      filter:
        configuration:
          project:
            userProjects:
              user_id:
                _eq: X-HASURA-USER-ID
    role: reader
    table:
      name: configuration_parameter
      schema: public
  type: create_select_permission
- args:
    role: reader
    table:
      name: configuration_parameter
      schema: public
  type: drop_select_permission
- args:
    role: tester
    table:
      name: configuration_parameter
      schema: public
  type: drop_select_permission
- args:
    role: manager
    table:
      name: configuration_extension
      schema: public
  type: drop_select_permission
- args:
    role: reader
    table:
      name: configuration_extension
      schema: public
  type: drop_select_permission
- args:
    role: tester
    table:
      name: configuration_extension
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: true
      columns:
      - configuration_id
      - name
      - value
      filter:
        _and:
        - configuration:
            is_deleted:
              _eq: false
        - configuration:
            project:
              is_deleted:
                _eq: false
        - configuration:
            project:
              userProjects:
                user_id:
                  _eq: X-Hasura-User-Id
    role: manager
    table:
      name: configuration_envvars
      schema: public
  type: create_select_permission
- args:
    role: manager
    table:
      name: configuration_envvars
      schema: public
  type: drop_select_permission
