table:
  name: configuration
  schema: public
object_relationships:
- name: configuration_type
  using:
    foreign_key_constraint_on: type_slug
- name: project
  using:
    foreign_key_constraint_on: project_id
- name: test_source
  using:
    foreign_key_constraint_on: test_source_id
array_relationships:
- name: configuration_envvars
  using:
    foreign_key_constraint_on:
      column: configuration_id
      table:
        name: configuration_envvars
        schema: public
- name: configuration_extensions
  using:
    foreign_key_constraint_on:
      column: configuration_id
      table:
        name: configuration_extension
        schema: public
- name: configuration_parameters
  using:
    foreign_key_constraint_on:
      column: configuration_id
      table:
        name: configuration_parameter
        schema: public
- name: executions
  using:
    foreign_key_constraint_on:
      column: configuration_id
      table:
        name: execution
        schema: public
select_permissions:
- permission:
    allow_aggregations: true
    columns:
    - id
    - name
    - project_id
    - performed
    - created_by_id
    - type_slug
    - test_source_id
    - instances
    - is_deleted
    - has_pre_test
    - has_post_test
    - has_load_tests
    - has_monitoring
    - monitoring_chart_configuration
    filter:
      _and:
      - project:
          userProjects:
            user_id:
              _eq: X-Hasura-User-Id
      - project:
          is_deleted:
            _eq: false
      - is_deleted:
          _eq: false
  role: manager
- permission:
    allow_aggregations: true
    columns:
    - id
    - name
    - project_id
    - performed
    - created_by_id
    - type_slug
    - test_source_id
    - instances
    - is_deleted
    - has_pre_test
    - has_post_test
    - has_load_tests
    - has_monitoring
    - monitoring_chart_configuration
    filter:
      _and:
      - project:
          userProjects:
            user_id:
              _eq: X-Hasura-User-Id
      - project:
          is_deleted:
            _eq: false
      - is_deleted:
          _eq: false
  role: reader
- permission:
    allow_aggregations: true
    columns:
    - id
    - name
    - project_id
    - performed
    - created_by_id
    - type_slug
    - test_source_id
    - instances
    - is_deleted
    - has_pre_test
    - has_post_test
    - has_load_tests
    - has_monitoring
    - monitoring_chart_configuration
    filter:
      _and:
      - project:
          userProjects:
            user_id:
              _eq: X-Hasura-User-Id
      - project:
          is_deleted:
            _eq: false
      - is_deleted:
          _eq: false
  role: tenantadmin
- permission:
    allow_aggregations: true
    columns:
    - id
    - name
    - project_id
    - performed
    - created_by_id
    - type_slug
    - test_source_id
    - instances
    - is_deleted
    - has_pre_test
    - has_post_test
    - has_load_tests
    - has_monitoring
    - monitoring_chart_configuration
    filter:
      _and:
      - project:
          userProjects:
            user_id:
              _eq: X-Hasura-User-Id
      - project:
          is_deleted:
            _eq: false
      - is_deleted:
          _eq: false
  role: tester
- permission:
    columns:
    - created_by_id
    - has_load_tests
    - has_monitoring
    - has_post_test
    - has_pre_test
    - id
    - instances
    - name
    - performed
    - project_id
    - test_source_id
    - type_slug
    filter:
      _and:
      - executions:
          id:
            _eq: X-Hasura-Testruner-Id
      - project:
          is_deleted:
            _eq: false
      - is_deleted:
          _eq: false
  role: testrunner
