SECRET_KEY = 'SECRET_KEY'
JWT_ALGORITHM = 'JWT_ALGORITHM'

ROLE_ADMIN = 'admin'
ROLE_MANAGER = 'manager'
ROLE_READER = 'reader'

TENANT_ID = '1'

TESTRUN_PREPARING = 'PENDING'
TESTRUN_PREPARING_FAILED = 'PREPARING FAILED'
TESTRUN_STARTED = 'STARTED'
TESTRUN_RUNNING = 'RUNNING'
TESTRUN_FINISHED = 'FINISHED'

TESTRUN_EXTREME = 'extreme_load'
TESTRUN_TYPES = (TESTRUN_EXTREME,)
