- args:
    permission:
      allow_aggregations: false
      columns:
      - id
      - configuration_id
      - value
      - parameter_id
      filter: {}
      limit: null
    role: manager
    table:
      name: configuration_parameter
      schema: public
  type: create_select_permission
