- args:
    name: configurationParametersByparameterId
    table:
      name: parameter
      schema: public
    using:
      foreign_key_constraint_on:
        column: parameter_id
        table:
          name: configuration_parameter
          schema: public
  type: create_array_relationship
