- args:
    permission:
      columns:
      - value
      filter:
        configuration:
          project:
            userProjects:
              user_id:
                _eq: X-HASURA-USER-ID
    role: manager
    table:
      name: configuration_parameter
      schema: public
  type: create_update_permission
