- args:
    permission:
      allow_aggregations: false
      columns:
      - id
      - name
      - description
      filter: {}
      limit: null
    role: reader
    table:
      name: configuration_type
      schema: public
  type: create_select_permission
