- args:
    sql: CREATE EXTENSION IF NOT EXISTS pgcrypto;
  type: run_sql
- args:
    sql: CREATE TABLE "public"."configuration_parameter"("id" uuid NOT NULL UNIQUE
      DEFAULT gen_random_uuid(), "configuration_id" uuid NOT NULL, "parameter" uuid
      NOT NULL, "value" text NOT NULL, PRIMARY KEY ("id") );
  type: run_sql
- args:
    name: configuration_parameter
    schema: public
  type: add_existing_table_or_view
