- args:
    permission:
      allow_upsert: true
      check:
        configuration:
          project:
            userProjects:
              user_id:
                _eq: X-HASURA-USER-ID
      columns:
      - configuration_id
      - id
      - parameter_id
      - value
      set: {}
    role: manager
    table:
      name: configuration_parameter
      schema: public
  type: create_insert_permission
