- args:
    name: testCreators
    table:
      name: configuration
      schema: public
    using:
      foreign_key_constraint_on:
        column: configuration_id
        table:
          name: test_creator_configuration_m2m
          schema: public
  type: create_array_relationship
