- args:
    role: manager
    table:
      name: configuration
      schema: public
  type: drop_update_permission
- args:
    permission:
      columns:
      - name
      filter:
        project:
          userProjects:
            user_id:
              _eq: X-HASURA-USER-ID
      localSet:
      - key: ""
        value: ""
      set: {}
    role: manager
    table:
      name: configuration
      schema: public
  type: create_update_permission
