- args:
    sql: CREATE EXTENSION IF NOT EXISTS pgcrypto;
  type: run_sql
- args:
    sql: ALTER TABLE "public"."test_creator_configuration_m2m" ADD COLUMN "id" uuid
      NOT NULL DEFAULT gen_random_uuid()
  type: run_sql
