- args:
    sql: ALTER TABLE "public"."test_creator_configuration_m2m" DROP CONSTRAINT "test_creator_configuration_m2m_id_key"
  type: run_sql
- args:
    sql: COMMENT ON COLUMN "public"."test_creator_configuration_m2m"."id" IS 'undefined'
  type: run_sql
