- args:
    name: configurations
    table:
      name: repository
      schema: public
    using:
      foreign_key_constraint_on:
        column: repository_id
        table:
          name: configuration
          schema: public
  type: create_array_relationship
