- args:
    role: reader
    table:
      name: configuration_parameter
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns:
      - configuration_id
      - id
      - parameter_id
      - value
      filter:
        configuration:
          project:
            userProjects:
              user_id:
                _eq: X-HASURA-USER-ID
    role: reader
    table:
      name: configuration_parameter
      schema: public
  type: create_select_permission
