- args:
    permission:
      check:
        project:
          userProjects:
            user_id:
              _eq: X-HASURA-USER-ID
      columns:
      - name
      - project_id
      localPresets:
      - key: created_by_id
        value: x-hasura-USER-ID
      - key: ""
        value: ""
      set:
        created_by_id: x-hasura-USER-ID
    role: manager
    table:
      name: configuration
      schema: public
  type: create_insert_permission
