- args:
    role: manager
    table:
      name: configuration
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns:
      - id
      - name
      - project_id
      filter:
        _and:
        - project:
            userProjects:
              user_id:
                _eq: X-Hasura-User-Id
        - project:
            is_deleted:
              _eq: false
        - is_deleted:
            _eq: false
    role: manager
    table:
      name: configuration
      schema: public
  type: create_select_permission
