- args:
    sql: CREATE EXTENSION IF NOT EXISTS pgcrypto;
  type: run_sql
- args:
    sql: CREATE TABLE "public"."configuration_envvars"("id" uuid NOT NULL UNIQUE DEFAULT
      gen_random_uuid(), "configuration_id" uuid NOT NULL, "name" text NOT NULL, "value"
      text NOT NULL, PRIMARY KEY ("id") , FOREIGN KEY ("configuration_id") REFERENCES
      "public"."configuration"("id") ON UPDATE restrict ON DELETE restrict);
  type: run_sql
- args:
    name: configuration_envvars
    schema: public
  type: add_existing_table_or_view
