- args:
    name: configuration_extensions
    table:
      name: configuration
      schema: public
    using:
      foreign_key_constraint_on:
        column: configuration_id
        table:
          name: configuration_extension
          schema: public
  type: create_array_relationship
